### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by mgaroub**

### CODE REVIEW

**Comment by sbabicki** [comment]
@mgaroub Do we need to cite where this was copied from?

**Comment by mgaroub** [comment]
Check Attribution

**Comment by mgaroub** [comment]
> @mgaroub Do we need to cite where this was copied from?

Check Attribution

**Comment by sbabicki** [comment]
Ohhh, my bad. Thought it was copied from Tiff's example but I guess you went straight to a different source 👍

**Pull request merged**
